"""empty message

Revision ID: 1f1f1cbd01a2
Revises: fc555ec799e4
Create Date: 2023-03-12 23:42:31.383068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f1f1cbd01a2'
down_revision = 'fc555ec799e4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('battle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attacker_id', sa.Integer(), nullable=True),
    sa.Column('defender_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['attacker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['defender_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('battle')
    # ### end Alembic commands ###
